### ISSUE TITLE
How can I get real index or current page number in my app?

### ISSUE THREAD

**Issue by nasta** [janholinka/bs-table#9]
Bs-table is really useful for me. I can use $index to get current index in page, but how can I get real index in hole array?
Or how can I get current page and page size which could help me to calculate current index?

**Comment by janholinka** [comment]
Hi,
I am glad that bs-table is helpful for you. Now, bs-table doesn't support option to get index of current page but you can write custom on click function in angular controller like below:
var paginationLink = angular.element(".pagination a");paginationLink.bind("click", function(e){    alert(e.target.innerText);});
I will implement this feature ASAP because it sounds like a good idea. 

Regards,
Jan

Date: Wed, 21 Jan 2015 00:35:22 -0800

**Comment by janholinka** [comment]
Hi,
I am glad that bs-table is helpful for you. Now, bs-table doesn't support option to get index of current page but you can write custom on click function in angular controller like below:

```
var paginationLink = angular.element(".pagination a");
paginationLink.bind("click", function(e){
    alert(e.target.innerText);
});
```

I will implement this feature ASAP because it sounds like a good idea.

Regards,
Jan

**Comment by nasta** [comment]
Thank you a lot, really appreciate about it.

Best wishes,
nasta
